//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDDFine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GibddEntities : DbContext
    {
        private static GibddEntities context;
        public static GibddEntities GetContext()
        {
            if (context == null)
                return new GibddEntities();
            return context;
        }
        public GibddEntities()
            : base("name=GibddEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Водители> Водители { get; set; }
        public virtual DbSet<Машины> Машины { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<СотрудникиГИБДД> СотрудникиГИБДД { get; set; }
        public virtual DbSet<Страховка> Страховка { get; set; }
        public virtual DbSet<Штрафы> Штрафы { get; set; }
    }
}
