//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDDFine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class СотрудникиГИБДД
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public СотрудникиГИБДД()
        {
            this.Штрафы = new HashSet<Штрафы>();
        }
    
        public int TabelNum { get; set; }
        public string FIO { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateBith { get; set; }
        public string Doljnost { get; set; }
        public int Oklad { get; set; }
        public string HomeAdress { get; set; }
        public string PhoneNum { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Штрафы> Штрафы { get; set; }
    }
}
