//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDDFine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Страховка
    {
        public int StrahovoiNomer { get; set; }
        public int Owner { get; set; }
        public string Avto { get; set; }
    
        public virtual Водители Водители { get; set; }
        public virtual Машины Машины { get; set; }
    }
}
